#!/bin/bash

# --- Script Version Info --- #
ScriptVersion=1.3.9
ScriptDEBUG=0

# --- Script Pfade --- #
ScriptHome=$(echo $HOME)
ScriptDownloadPath="${ScriptHome}/Desktop/Kext-Updates"
ScriptTmpPath="/tmp"
curl -sS -o ${ScriptTmpPath}/overview.htm https://kextupdater.slsoft.de/overview.htm
sed -ib "s/intelmausiethernet-230/intelmausiethernet-230d0/g" ${ScriptTmpPath}/overview.htm
kextstat > ${ScriptTmpPath}/kextstats
./BDMESG |grep "Clover revision" |sed -e "s/.*revision:\ /Clover\ (/g" -e "s/\ on.*/)/g" >> ${ScriptTmpPath}/kextstats

#========== Kext Array ==========#
## Script Name,kextstat Name, echo Name, Ersatz Name
#
kextArray=(
  "acpibatterymanager","org.rehabman.driver.AppleSmartBatteryManager","ACPI BatteryManager",""
  "airportbrcmfixup","BrcmWLFixup","BrcmWLFixup","AirportBrcmFixup"
  "airportbrcmfixup","AirportBrcmFixup","AirportBrcmFixup",""
  "applealc","ALC","AppleALC",""
  "atherose2200ethernet","AtherosE2200","AtherosE2200Ethernet",""
  "azulpatcher4600","AzulPatcher4600","AzulPatcher4600",""
  "bt4lecontiunityfixup","BT4LEContiunityFixup","BT4LEContiunityFixup",""
  "clover","Clover","Clover Bootloader",""
  "codeccommander","CodecCommander","CodecCommander",""
  "coredisplayfixup","CoreDisplayFixup","CoreDisplayFixup",""
  "cpufriend","CPUFriend","CPUFriend",""
  "fakepciid","FakePCIID","FakePCIID",""
  "fakesmc","FakeSMC","FakeSMC",""
  "hibernationfixup","HibernationFixup","HibernationFixup",""
  "intelgraphicsdvmtfixup","IntelGraphicsDVMTFixup","IntelGraphicsDVMTFixup",""
  "intelgraphicsfixup","IntelGraphicsFixup","IntelGraphicsFixup",""
  "intelmausiethernet","IntelMausi","IntelMausiEthernet",""
  "lilu","Lilu","Lilu",""
  "nightshiftunlocker","NightShiftUnlocker","NightShiftUnlocker",""
  "nvidiagraphicsfixup","NvidiaGraphicsFixup","NvidiaGraphicsFixup",""
  "realtekrtl8111","RealtekRTL8111","RealtekRTL8111",""
  "shiki","Shiki","Shiki",""
  "usbinjectall","USBInjectAll","USBInjectAll",""
  "voodoohda","VoodooHDA","VoodooHDA",""
  "voodooI2C","VoodooI2C","VoodooI2C",""
  "whatevergreen","WhateverGreen","WhateverGreen",""
  "intelmausiethernet","AppleIntelE1000","AppleIntelE1000","IntelMausiEthernet"
  "nvidiagraphicsfixup","LibValFix","NVWebDriverLibValFix","NvidiaGraphicsFixup"
  "voodoops2","PS2Controller","VoodooPS2",""
)

#==== Ausgabe Kopfzeilen ==============
function _printHeader()
{
  echo "==========================================================="
  echo "                  K E X T - U P D A T E R                  "
  echo "==========================================================="
  echo " "

  source special1

}
#==== Ausgabe Fusszeile ==============
function _printFooter()
{
  echo " "
  echo "==========================================================="
  echo "                          D O N E                          "
  echo "==========================================================="
  echo " "
  afplay done.mp3
}
#==== Hilfsfunktion Update ==============
function _toUpdate()
{
  _PRINT_MSG "Update available!\n
Your Version = $lecho\n
Server Version = $recho\n
Downloading Version $recho to your Desktop into the Folder Kext-Updates\n-----------------------------------------------------------\n\n"
}
#==== Hilfsfunktion kein Doppelt ==============
function _dupeKext()
{
  _PRINT_MSG "The latest Version is already downloaded to your Desktop. If its already installed please remove the Folder from your Desktop.\n-----------------------------------------------------------\n\n"
}
#==== Hilfsfunktion kein Kext ==============
function _noUpdate()
{
  _PRINT_MSG "√ You are up to date ($lecho)\n-----------------------------------------------------------\n\n"
}
#==== Hilfsfunktion veralteter Kext ==============
function _obsoleteKext()
{
  _PRINT_MSG "Attention !!!\nPlease make sure to delete your old ${data[2]} and use ${data[3]} instead\n"
}
#==== Hilfsfunktion Message ==============
function _PRINT_MSG()
{
  local message=$1
  printf "${message}\n"
}
#==== Hilfsfunktion Debug ==============
function _DEBUG_PRINT()
{
  if [[ "$ScriptDEBUG" == "1" ]];
    then
      printf "DebugModus $1\n"
  fi
}
#============================== KextUpdate ==============================
function _kextUpdate()
{
  for kextList in "${kextArray[@]}"
    do
       IFS=","
       data=($kextList)
      _DEBUG_PRINT $data
      name=${data[0]}
      lecho=`cat ${ScriptTmpPath}/kextstats |grep ${data[1]} | sed -e "s/.*(//g" -e "s/).*//g"`
      local=`echo $lecho | sed -e "s/\.//g"`

      if ! [[ $local = "" ]]; then
        echo "Checking ${data[2]} ..."
        if ! [[ -z ${data[3]} ]] ; then # veralteter Kext
          _obsoleteKext
        fi
        recho=`cat ${ScriptTmpPath}/overview.htm |grep $name |sed -e "s/.*-//g"`
        remote=`echo $recho | sed -e "s/\.//g"`
        if [ -f ${ScriptDownloadPath}/${name}/.version.htm ]; then
          dupe=`cat ${ScriptDownloadPath}/${name}/.version.htm`
          if [[ $dupe = $remote ]]; then
            _dupeKext
          fi
        else
        if [[ $local != $remote ]]; then
          mkdir -p ${ScriptDownloadPath} ${ScriptDownloadPath}/${name}
          _toUpdate
          curl -sS -o ${ScriptTmpPath}/${name}.zip https://kextupdater.slsoft.de/${name}/${name}.zip
          curl -sS -o ${ScriptDownloadPath}/$name/.version.htm https://kextupdater.slsoft.de/${name}/version.htm
          unzip -o -q ${ScriptTmpPath}/${name}.zip -d ${ScriptDownloadPath}/${name}
        else
          _noUpdate
        fi
      fi
    fi
done
}
#============================== Hauptfunktion ==============================
function main()
{
  _printHeader
  _DEBUG_PRINT "Anfang Debug Ausgabe\n"
  _kextUpdate
  _DEBUG_PRINT "Ende Debug Ausgabe\n"
  _printFooter
}
#============================== START ==============================
main
exit 0
#=============================================================